### ISSUE TITLE
Weird .mp4 video after converting raw .yuv video with ffmpeg

### ISSUE THREAD

**Issue by predictwise** [JihyongOh/JSI-GAN#12]
Hi @sooyekim @JihyongOh 

Thanks for your great work!

I am using following command to convert raw .yuv video to .mp4, but the result is very weird:

```
ffmpeg -f rawvideo -vcodec rawvideo -s 3840x2160 -r 25 -pix_fmt yuv420p -i ./test_img_dir/JSI-GAN_x2_exp1/result.yuv -c:v libx264 -preset ultrafast -qp 0 ./test_img_dir/JSI-GAN_x2_exp1/result.mp4
```

![Screenshot from 2020-09-29 17-44-55](https://user-images.githubusercontent.com/12490765/94582265-55959a00-027c-11eb-863e-e6b6ba56a0a5.png)

Did I do something wrong?

Kind regards,
Oliver

**Comment by sooyekim** [comment]
@predictwise 
Hi Oliver!
Apologies for the late reply.

I converted the .yuv files to .mp4 using the commands specified [here](https://github.com/sooyekim/Deep-SR-ITM/issues/1#issuecomment-528864377). I used x265 as the codec, which supports HDR.
Note that the default codec on ffmpeg may not support HDR.

LMK if you have any other questions, thanks!
Soo Ye
