### ISSUE TITLE
Inverse tone mapping without Super Resolution.

### ISSUE THREAD

**Issue by sujeet-gandhi** [JihyongOh/JSI-GAN#14]
Hi @sooyekim ,

Thanks for your great work!

Let's say we just want a model to covert SDR images to HDR images without applying super resolution on them. Can such a model be obtained by modifying the provided code? If yes, then which modifications would you suggest? 

Thanks much.

**Comment by sooyekim** [comment]
Hi @sujeet-gandhi ,

Thanks for the interest in our work!
A model without super-resolution can be simply trained by setting the scale_factor flag to 1.
We've only provided x2 models, so you would have to train this model first before testing on your own images/videos.

Thanks!

**Comment by sujeet-gandhi** [comment]
Hi @sooyekim 

Thanks for the quick reply.
So, just to confirm my understanding,  `SR HDR .mat` files should be converted to `LR-HDR.mat` files by resizing right?
Will a simple resize work or should i go for `Bilinear interpolation` for scaling `SR-HDR` images to `LR-HDR` images ?

Thanks.

**Comment by sooyekim** [comment]
Hi @sujeet-gandhi ,
I haven't tried this training scenario, but I think imresize on Matlab with default configurations (bicubic) should work.
Thanks!

**Comment by 8bignic8** [comment]
> Hi @sujeet-gandhi ,
> 
> Thanks for the interest in our work!
> 
> A model without super-resolution can be simply trained by setting the scale_factor flag to 1.
> Also, the .mat training data should be resized (maybe by imresize function in Matlab?) so that SDR patches and HDR patches are of the same resolution.
> We've only provided x2 and x4 models, so you would have to train this model first before testing on your own images/videos.
> 
> Thanks!

I tried that but I get the error: 
ValueError: Attr 'block_size' of 'DepthToSpace' Op passed 1 less than minimum 2.

If I use --scale_factor 2 this Message is not showing up and the training starts.

**Comment by sooyekim** [comment]
Hi @8bignic8 ,
I guess TF 'DepthToSpace' Op doesn't work for 1..
In this case, you can just comment [this line](https://github.com/JihyongOh/JSI-GAN/blob/b636463385fb693effe43cecc28867f4308e3e20/net.py#L104) since it's an identity function anyway with sf=1.
LMK if you run into any other errors!
