### ISSUE TITLE
I got some severe artifact when I test on my own sdr video

### ISSUE THREAD

**Issue by hahahaprince** [JihyongOh/JSI-GAN#15]
Hi~ @sooyekim @JihyongOh @ryul99 Thanks for your great work! 

When I test JSI-GAN on my own SDR data, some HDR results shows artifact like following picture. Do you know the reason for this bad case? And do you have any suggestions for solving this problem？
Looking forward to your reply！
### case 1
- INPUT SDR:
![input SDR](https://user-images.githubusercontent.com/22274077/106870520-2b615680-670c-11eb-8baa-ac3d62854176.png)
- OUTPUT HDR:
![HDR result](https://user-images.githubusercontent.com/22274077/106870363-fe14a880-670b-11eb-9c44-d04a41197d3e.png)
### case 2
- INPUT SDR:
![INPUT SDR 2](https://user-images.githubusercontent.com/22274077/106872270-138ad200-670e-11eb-8ebf-9027bba15f7c.png)
- OUTPUT HDR:
![HDR result 2](https://user-images.githubusercontent.com/22274077/106872333-243b4800-670e-11eb-8c1c-a9adc4bf153a.png)

**Comment by sooyekim** [comment]
Hi @hahahaprince ,
Thanks for the interest in our work!

I haven't seen such artifacts before, and I'm not sure why this would happen.
Do all results look weird or just some of the frames? 
Also, how are you visualizing these HDR examples? (Our prediction is in the range of 0-1023 and in the HDR10 format)

**Comment by hahahaprince** [comment]
> Hi @hahahaprince ,
> Thanks for the interest in our work!
> 
> I haven't seen such artifacts before, and I'm not sure why this would happen.
> Do all results look weird or just some of the frames?
> Also, how are you visualizing these HDR examples? (Our prediction is in the range of 0-1023 and in the HDR10 format)

Just some frames.
It looks the same when I watched yuv444p10le by YUVIEW and video encoded in HDR10 format by VLC player. 
If you are interested on this problem, I will send the input frames to you. Thanks for your reply!
