### ISSUE TITLE
test PSNR is not as same as the paper

### ISSUE THREAD

**Issue by haifangqin** [JihyongOh/JSI-GAN#19]
hi, It is very appreciated for you to open your work!

I am now trying to re-implement your work and found that

use the pretrained weights to inferecnce the test mat will get the low PSNR:

the instruction I use is:
**python main.py --phase test_mat --scale_factor 2 --test_data_path_LR_SDR ./data/test/testset_SDR_x2.mat --test_data_path_HR_HDR ./data/test/testset_HDR.mat**

 <Test> [  20/  28]-th images, time: 7.6218(minutes), test_PSNR: -8.98004621[dB]
 <Test> [  21/  28]-th images, time: 7.8429(minutes), test_PSNR: -9.02793094[dB]
 <Test> [  22/  28]-th images, time: 8.0659(minutes), test_PSNR: -9.09201666[dB]
 <Test> [  23/  28]-th images, time: 8.2833(minutes), test_PSNR: -9.27487238[dB]
 <Test> [  24/  28]-th images, time: 8.5779(minutes), test_PSNR: -9.01922608[dB]
 <Test> [  25/  28]-th images, time: 8.9090(minutes), test_PSNR: -8.93554880[dB]
 <Test> [  26/  28]-th images, time: 9.2477(minutes), test_PSNR: -8.83121465[dB]
 <Test> [  27/  28]-th images, time: 9.5102(minutes), test_PSNR: -8.97071717[dB]
######### Estimated Inference Time (per 4K frame): 2.20851422[s]  #########

**the pretrained weights I use is JSI-GAN_x2_exp1**

I think if I do something wrong to get these results?

looking forward to your reply!

**Comment by sooyekim** [comment]
Hi @haifangqin ,

Glad to hear that you found our work useful!
Apologies for the late reply, I wanted to try running the code before replying to this issue.

I re-downloaded the code and tried running it on a different computer with the same command you used, and got an average PSNR of 35.78 dB which is slightly higher than the value reported in our paper (35.73 dB for x2).

Perhaps it's a version issue? Our code was tested under TF 1.13 (+ other version details are in the README file).
- Soo Ye

**Comment by haifangqin** [comment]
hi，I have figure out what is happening, is the checkpoint do not load accuratly. thanks!

**Comment by sooyekim** [comment]
Thanks for the update, glad you figured out! Closing this issue
