### ISSUE TITLE
Please add requirements.txt or environment.yml

### ISSUE THREAD

**Issue by ryul99** [JihyongOh/JSI-GAN#3]
Thank you for the nice work and for opening the codes! 
But there is no requirements.txt or environment.yml, I have trouble in installing the dependencies.
Could you please add requirements.txt or environment.yml?

**Comment by sooyekim** [comment]
Hi @ryul99 ,

I have just added a requirements.txt file in the repository.
Hope this helps!

Thanks,
Soo Ye
