### ISSUE TITLE
Weired results !?

### ISSUE THREAD

**Issue by aligoglos** [JihyongOh/JSI-GAN#6]
Hi, I've tried to run your code on `RGB `images. So changed your code like this:
```
yuv = cv2.imread(data_path_test[index])
yuv = cv2.cvtColor(yuv,cv2.COLOR_BGR2YUV)
img = np.expand_dims(yuv, axis=0)
```
And then saved output like this:
```
out = test_pred = np.squeeze(test_pred_full)
out = np.clip(out, 0, 1) * 255
out = out.astype('uint8')
out = cv2.cvtColor(out,cv2.COLOR_YUV2BGR)
cv2.imwrite(f"./results/{index}.jpg",out)
```
but outputs are weird like this:
![0](https://user-images.githubusercontent.com/3922472/75965458-19fd4200-5ede-11ea-9fe4-2cbf59752974.jpg)

**Comment by sooyekim** [comment]
Hi @aligoglos ,

Sorry for the late reply.

First of all, how do you intend to view the output on your device? Does it support HDR? In that case, you would want to **encode** the YUV video frames to an MP4 file as in [this issue](https://github.com/sooyekim/Deep-SR-ITM/issues/1#issuecomment-528864377).

As for your code:
- The prediction is actually an HDR video frame in the HDR10 standard (10 bits/pixel, BT.2020 color container, PQ-OETF). Therefore, when normalizing, you should be multiplying with 1023, not 255. 
- Also, the conversion matrix for going from YUV2020 to RGB2020 is different to the conventional YUV709 to RGB709 conversion (cv2.COLOR_YUV2BGR). You could refer to the [Common Test Conditions for HDR/WCG Video Coding Experiments](https://mpeg.chiariglione.org/standards/mpeg-h/high-efficiency-video-coding/n15793-common-test-conditions-hdrwcg-video-coding) document officially released by MPEG, if you wish to implement it on your own.

However, my suggestion is to encode the video before viewing on an HDR device.

Thanks,
Soo Ye
